---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_facts:
      cloud: ospcloud

  - name: Delete instances
    os_server:
      cloud: ospcloud
      state: absent
      name: "{{ item.name }}"
      image: "{{ item.image }}"
    loop: "{{ openstack_servers }}"

